### ISSUE TITLE
Add Support for MSVC compiler

### ISSUE THREAD

**Issue by Lorac** [teeks99/boost-cpp-docker#1]
Is that a possibility?

**Comment by teeks99** [comment]
I assume you mean Microsoft's MSVC compiler (and MSCV was a typo). Unfortunately I don't believe that will run on linux...maybe under wine? Anyway, to work on Docker it has to be on linux.

**Comment by Lorac** [comment]
Something like that?

https://stackoverflow.com/questions/36639422/microsoft-compiler-in-docker

**Comment by Lorac** [comment]
It looks like it's possible with a `microsoft/windowsservercore` base image

**Comment by teeks99** [comment]
So I had never really thought about supporting windows in this repo....all the images in here are specific to boost on linux, but I'm not sure there is a fundamental reason not to. However, before hitting that step we need to get an image with the msvc compiler/toolchain on it (the linux images in here pull from the respective [gcc](https://github.com/teeks99/gcc-ubuntu-docker) and [clang](https://github.com/teeks99/clang-ubuntu-docker) images). My interest has been peaked enough that I'd like to put together one of these, but my amount of free time is pretty low, so it will probably be months before I get around to it. If you want to put together a docker image with the tool chain on it, I'd be more than happy to add an image here with the appropriate boost config. This would be really useful for my project that consumes these images for running the [boost unit tests](https://github.com/teeks99/boost-build/tree/master/Regression), right now I have manually created VM images with *all* the Visual Studios installed on them to run those. Docker images would be much better.

**Comment by Lorac** [comment]
Ok, I'll see what I can do

**Comment by teeks99** [comment]
This work has been started in the [msvc-win-docker](https://github.com/teeks99/msvc-win-docker) repo, but hasn't been very smooth. Once that is working, boost test images can be pulled in here, but we'll open a new issue at that point.
